#!/usr/bin/env bash
# Install and configure haproxy

load_balancer="\
frontend myfrontend
    bind *:80
    mode http
    default_backend webservers

backend mybackend
    balance roundrobin
    server 225838-web-01 52.91.168.104:80 check
    server 225838-web-02 100.24.253.204:80 check
"
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
