#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

if [ -e "school" ]; then
    echo "School file exists"
    
    if [ -s "school" ]; then
        echo "School file is not empty"
    else
        echo "School file is empty"
    fi
    
    if [ -f "school" ]; then
        echo "School file is a regular file"
    fi
else
    echo "School file does not exist"
fi
