#!/usr/bin/env bash

# Step 1: Stop the Apache web server if it's running
pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
# Step 4: Update the Nginx default site configuration to use port 8080 instead of 80
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
